//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingBook.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Ingredient
    {
        private string quantityTypeVariant { get; set; }
        public string Name { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<long> RecipeID { get; set; }
        public long ID { get; set; }
        public Nullable<long> TypeID { get; set; }
    
        public virtual QuantityType QuantityType { get; set; }
        public virtual Recipe Recipe { get; set; }

        public override string ToString()
        {
            using (var contex = new CookingBookEntities1())
            {
                quantityTypeVariant = contex.QuantityTypes.Where(x => x.ID == TypeID).FirstOrDefault().Name;
                if(Quantity != 1)
                {
                    if ((Quantity < 1 || (Quantity < 10 || Quantity > 20) && Quantity % 10 > 1 && Quantity % 10 < 5) && (quantityTypeVariant == "Szklanka" || quantityTypeVariant == "Sztuka" || quantityTypeVariant == "£y¿eczka" || quantityTypeVariant == "£y¿ka"))
                    {
                        quantityTypeVariant = quantityTypeVariant.Remove(quantityTypeVariant.Length - 1);
                        quantityTypeVariant += "i";
                    }

                    if (Quantity > 1 && (Quantity % 10 < 2 || Quantity % 10 > 5 || (Quantity < 10 || Quantity > 20)) && (quantityTypeVariant == "Szklanka" || quantityTypeVariant == "Sztuka" || quantityTypeVariant == "£y¿eczka" || quantityTypeVariant == "£y¿ka"))
                    {
                        if (quantityTypeVariant == "Sztuka")
                            quantityTypeVariant = quantityTypeVariant.Remove(quantityTypeVariant.Length - 1);
                        else
                        {
                            quantityTypeVariant = quantityTypeVariant.Remove(quantityTypeVariant.Length - 2);
                            quantityTypeVariant += "ek";
                        }
                    }
                }
                return Name + ", " + Quantity + " " + quantityTypeVariant;
            }
        }
    }
}
